CREATE TABLE assets (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol text NOT NULL UNIQUE
);

CREATE TABLE history_points (
    asset_id integer NOT NULL,
    timestamp timestamp NOT NULL,
    value decimal NOT NULL,

    FOREIGN KEY (asset_id) REFERENCES assets (id)
);

INSERT INTO assets (symbol) VALUES
    ('EURUSD'),
    ('USDJPY'),
    ('GBPUSD'),
    ('AUDUSD'),
    ('USDCAD');
